In [1]:
import numpy as numpy
import pandas as pd

In [2]:
df = pd.read_csv('raw_data.csv')

In [3]:
df.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,...,City,Time_taken (min),Day,Month,Order_Hour,Order_Min,Pick_Hour,Pick_Min,Pickup_Duration,Distance
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,Fog,Jam,2,Snack,...,Metropolitian,46,12,2,21,55,22,10,15.0,10.280582
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,Stormy,High,1,Meal,...,Metropolitian,23,13,2,14,55,15,5,10.0,6.242319
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,Sandstorms,Medium,1,Drinks,...,Metropolitian,21,4,3,17,30,17,40,10.0,13.787860
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,Sandstorms,Low,0,Buffet,...,Metropolitian,20,13,2,9,20,9,30,10.0,2.930258
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,Fog,Jam,1,Snack,...,Metropolitian,41,14,2,19,50,20,5,15.0,19.396618

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45571 entries, 0 to 45570
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Delivery_person_Age          45571 non-null  float64
 1   Delivery_person_Ratings      45571 non-null  float64
 2   Restaurant_latitude          45571 non-null  float64
 3   Restaurant_longitude         45571 non-null  float64
 4   Delivery_location_latitude   45571 non-null  float64
 5   Delivery_location_longitude  45571 non-null  float64
 6   Weather_conditions           45571 non-null  object
 7   Road_traffic_density         45571 non-null  object
 8   Vehicle_condition            45571 non-null  int64
 9   Type_of_order                45571 non-null  object
 10  Type_of_vehicle              45571 non-null  object
 11  multiple_deliveries          45571 non-null  float64
 12  Festival                     45571 non-null  object
 13  City                         45571 non-null  object
 14  Time_taken (min)             45571 non-null  int64
 15  Day                          45571 non-null  int64
 16  Month                        45571 non-null  int64
 17  Order_Hour                   45571 non-null  int64
 18  Order_Min                    45571 non-null  int64
 19  Pick_Hour                    45571 non-null  int64
 20  Pick_Min                     45571 non-null  int64
 21  Pickup_Duration              45571 non-null  float64
 22  Distance                     45571 non-null  float64
dtypes: float64(9), int64(8), object(6)
memory usage: 8.0+ MB

In [5]:
## Independent and dependent features
X = df.drop(labels=['Time_taken (min)'],axis=1)
Y = df[['Time_taken (min)']]

In [6]:
X

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,...,Festival,City,Day,Month,Order_Hour,Order_Min,Pick_Hour,Pick_Min,Pickup_Duration,Distance
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,Fog,Jam,2,Snack,...,No,Metropolitian,12,2,21,55,22,10,15.0,10.280582
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,Stormy,High,1,Meal,...,No,Metropolitian,13,2,14,55,15,5,10.0,6.242319
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,Sandstorms,Medium,1,Drinks,...,No,Metropolitian,4,3,17,30,17,40,10.0,13.787860
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,Sandstorms,Low,0,Buffet,...,No,Metropolitian,13,2,9,20,9,30,10.0,2.930258
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,Fog,Jam,1,Snack,...,No,Metropolitian,14,2,19,50,20,5,15.0,19.396618
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45566,30.0,4.8,26.902328,75.794257,26.912328,75.804257,Windy,High,1,Meal,...,No,Metropolitian,24,3,11,35,11,45,10.0,1.489846
45567,21.0,4.6,0.000000,0.000000,0.070000,0.070000,Windy,Jam,0,Buffet,...,No,Metropolitian,16,2,19,55,20,10,15.0,11.007735
45568,30.0,4.9,13.022394,80.242439,13.052394,80.272439,Cloudy,Low,1,Drinks,...,No,Metropolitian,11,3,23,50,0,5,1425.0,4.657195
45569,20.0,4.7,11.001753,76.986241,11.041753,77.026241,Cloudy,High,0,Snack,...,No,Metropolitian,7,3,13,35,13,40,5.0,6.232393
45570,23.0,4.9,23.351058,85.325731,23.431058,85.405731,Fog,Medium,2,Snack,...,No,Metropolitian,2,3,17,10,17,15,5.0,12.074396

In [7]:
# Define which columns should be ordinal-encoded and which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns
numerical_cols

Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Vehicle_condition',
       'multiple_deliveries', 'Day', 'Month', 'Order_Hour', 'Order_Min',
       'Pick_Hour', 'Pick_Min', 'Pickup_Duration', 'Distance'],
      dtype='object')

In [8]:
# Define the custom ranking for each ordinal variable
Weather_conditions_cat = ['Fog', 'Stormy', 'Sandstorms', 'Windy', 'Cloudy', 'Sunny']
Weather_conditions_cat.reverse()
Road_traffic_density_cat = ['Jam', 'High', 'Medium', 'Low']
Road_traffic_density_cat.reverse()
Type_of_order_cat = ['Drinks', 'Snack', 'Meal', 'Buffet']
Type_of_vehicle_cat = ['motorcycle', 'scooter', 'electric_scooter', 'bicycle']
Festival_cat = ['No', 'Yes']
City_cat = ['Metropolitian', 'Urban', 'Semi-Urban']
City_cat.reverse()
Weather_conditions_cat

['Sunny', 'Cloudy', 'Windy', 'Sandstorms', 'Stormy', 'Fog']

In [9]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OrdinalEncoder # Ordinal Encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [10]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    # ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())

    ]

)

# Categorigal Pipeline
cat_pipeline=Pipeline(
    steps=[
    # ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinalencoder',OrdinalEncoder(categories=[Weather_conditions_cat,Road_traffic_density_cat, Type_of_order_cat, Type_of_vehicle_cat, Festival_cat, City_cat])),
    ('scaler',StandardScaler())
    ]

)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)
])

In [11]:
## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=30)

In [12]:
X_train.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,...,Festival,City,Day,Month,Order_Hour,Order_Min,Pick_Hour,Pick_Min,Pickup_Duration,Distance
4617,37.0,4.8,17.459710,78.368855,17.549710,78.458855,Windy,Low,1,Drinks,...,No,Metropolitian,29,3,22,10,22,25,15.0,13.828993
33758,30.0,4.7,12.933284,77.615428,13.043284,77.725428,Sandstorms,Low,2,Buffet,...,No,Metropolitian,20,3,21,55,23,15,80.0,17.078029
31952,35.0,4.1,-9.982834,76.283268,10.062834,76.363268,Cloudy,Medium,2,Drinks,...,No,Metropolitian,18,2,18,45,19,0,15.0,2228.994152
22538,34.0,4.9,23.351489,85.324253,23.411489,85.384253,Sandstorms,Jam,1,Meal,...,No,Urban,30,3,21,55,22,0,5.0,9.056096
31972,35.0,4.4,22.527893,88.368628,22.537893,88.378628,Fog,High,0,Meal,...,No,Metropolitian,17,2,11,50,11,55,5.0,1.513700

In [13]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [14]:
X_train.head()

,num_pipeline__Delivery_person_Age,num_pipeline__Delivery_person_Ratings,num_pipeline__Restaurant_latitude,num_pipeline__Restaurant_longitude,num_pipeline__Delivery_location_latitude,num_pipeline__Delivery_location_longitude,num_pipeline__Vehicle_condition,num_pipeline__multiple_deliveries,num_pipeline__Day,num_pipeline__Month,...,num_pipeline__Pick_Hour,num_pipeline__Pick_Min,num_pipeline__Pickup_Duration,num_pipeline__Distance,cat_pipeline__Weather_conditions,cat_pipeline__Road_traffic_density,cat_pipeline__Type_of_order,cat_pipeline__Type_of_vehicle,cat_pipeline__Festival,cat_pipeline__City
0,1.299135,0.497113,0.053109,0.356875,0.012167,0.361821,-0.029429,0.439867,1.742440,0.039382,...,0.914940,-0.293547,-0.152090,-0.077226,-0.324355,-1.094010,-1.342687,-0.773744,-0.142172,0.534623
1,0.071624,0.195153,-0.500593,0.324116,-0.600666,0.327205,1.163391,-1.318664,0.708209,0.039382,...,1.111435,-0.860504,0.166393,-0.074304,0.256621,-1.094010,1.341706,0.753870,-0.142172,0.534623
2,0.948418,-1.616604,-3.303841,0.266195,-1.005980,0.262915,1.163391,0.439867,0.478380,-1.794562,...,0.325453,-1.710940,-0.152090,1.914783,-0.905331,-0.293123,-1.342687,-0.773744,-0.142172,0.534623
3,0.773059,0.799073,0.773830,0.659291,0.809316,0.688678,-0.029429,-1.318664,1.857354,0.039382,...,0.914940,-1.710940,-0.201087,-0.081518,0.256621,1.308649,0.446908,0.753870,-0.142172,-1.793560
4,0.948418,-0.710725,0.673082,0.791658,0.690514,0.830004,-1.222248,0.439867,0.363465,-1.794562,...,-1.246510,1.407324,-0.201087,-0.088301,1.418572,0.507763,0.446908,-0.773744,-0.142172,0.534623

In [15]:
## Model Training

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor, BaggingRegressor
from sklearn.svm import SVR
import xgboost as xgb
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [16]:
import numpy as np
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mse)
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [19]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet(),
    # 'NaiveBias':MultinomialNB(),
    'KNNR':KNeighborsRegressor(n_neighbors=5),
    'DecisionTree':DecisionTreeRegressor(random_state=42),
    'SVR linear':SVR(kernel='linear'),
    'SVR rbf':SVR(kernel='rbf'),
    'RandomForest':RandomForestRegressor(random_state=42),
    'AdaBoost':AdaBoostRegressor(),
    'Gradient Boosting':GradientBoostingRegressor(),
    'XGB':xgb.XGBRegressor(),
    'BaggingSVR':BaggingRegressor()
}

trained_model_list = {'Model_Name':[], 'Model': [], 'R2_Score': []}

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    trained_model_list['Model_Name'].append(list(models.keys())[i])
    trained_model_list['Model'].append(model)
    trained_model_list['R2_Score'].append(r2_square*100)

    # trained_model_list.update({'Model_Name': list(models.keys())[i], 'Model': model, 'R2_Score': r2_square*100})

    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 6.628328649226185
MAE: 5.241296779209684
R2 score 49.66256394868063
===================================


Lasso
Model Training Performance
RMSE: 7.0830190128246295
MAE: 5.65794860230042
R2 score 42.51959246194975
===================================


Ridge
Model Training Performance
RMSE: 6.628301299634357
MAE: 5.241286544155942
R2 score 49.66297934917213
===================================


Elasticnet
Model Training Performance
RMSE: 7.115901497665562
MAE: 5.700566863699857
R2 score 41.984655040480746
===================================


KNNR
Model Training Performance
RMSE: 6.531435216842319
MAE: 5.061688121708601
R2 score 51.123480672849865
===================================


DecisionTree
Model Training Performance
RMSE: 5.548287945149723
MAE: 4.194704505558806
R2 score 64.73036156706445
===================================

d:\Data Science\iNeuron\ML\Regression\Assignment 1\venv\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR linear
Model Training Performance
RMSE: 6.659979062218984
MAE: 5.2238946430071636
R2 score 49.18069151647813
===================================

d:\Data Science\iNeuron\ML\Regression\Assignment 1\venv\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR rbf
Model Training Performance
RMSE: 6.057171756417993
MAE: 4.700336591183362
R2 score 57.96386280657671
===================================

d:\Data Science\iNeuron\ML\Regression\Assignment 1\venv\lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForest
Model Training Performance
RMSE: 4.056415632344502
MAE: 3.2074063779988298
R2 score 81.14754473592734
===================================

d:\Data Science\iNeuron\ML\Regression\Assignment 1\venv\lib\site-packages\sklearn\utils\validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoost
Model Training Performance
RMSE: 6.050489691469696
MAE: 4.939953914673222
R2 score 58.05655731056599
===================================

d:\Data Science\iNeuron\ML\Regression\Assignment 1\venv\lib\site-packages\sklearn\ensemble\_gb.py:424: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Gradient Boosting
Model Training Performance
RMSE: 4.622048115530945
MAE: 3.69301402648934
R2 score 75.52335168650868
===================================


XGB
Model Training Performance
RMSE: 4.095167169535765
MAE: 3.2505366415779378
R2 score 80.78562363644608
===================================

d:\Data Science\iNeuron\ML\Regression\Assignment 1\venv\lib\site-packages\sklearn\ensemble\_bagging.py:509: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return column_or_1d(y, warn=True)

BaggingSVR
Model Training Performance
RMSE: 6.058348049460482
MAE: 4.702571144847928
R2 score 57.94753452039018
===================================

In [20]:
pd.DataFrame(trained_model_list)

,Model_Name,Model,R2_Score
0,LinearRegression,LinearRegression(),49.662564
1,Lasso,Lasso(),42.519592
2,Ridge,Ridge(),49.662979
3,Elasticnet,ElasticNet(),41.984655
4,KNNR,KNeighborsRegressor(),51.123481
5,DecisionTree,DecisionTreeRegressor(random_state=42),64.730362
6,SVR linear,SVR(kernel='linear'),49.180692
7,SVR rbf,SVR(),57.963863
8,RandomForest,"(DecisionTreeRegressor(max_features=1.0, rando...",81.147545
9,AdaBoost,"(DecisionTreeRegressor(max_depth=3, random_sta...",58.056557
10,Gradient Boosting,([DecisionTreeRegressor(criterion='friedman_ms...,75.523352
11,XGB,"XGBRegressor(base_score=None, booster=None, ca...",80.785624
12,BaggingSVR,"(SVR(), SVR(), SVR(), SVR(), SVR(), SVR(), SVR...",57.947535